AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bingsuUser

  Sample SAM Template for bingsuUser

Globals:
  Function:
    Timeout: 30
    Runtime: python3.8
    Environment:
      Variables:
        BINGSU_USER_TABLE_NAME: !Ref UserTable

Resources:
  TestFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: bingsuUser/
      Handler: app.lambda_handler
      
  AddUserFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: bingsuUser/
      Handler: app.add_user
      
  GetUserByIdFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: bingsuUser/
      Handler: app.get_user_by_id
      
  UpdateUserFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: bingsuUser/
      Handler: app.update_user

  GetAllUserRankingFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: bingsuUser/
      Handler: app.get_all_by_ranking
      
  AuthoriseUserFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: bingsuUser/
      Handler: app.authorise_user
            
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: username
          AttributeType: S
        - AttributeName: grab_points
          AttributeType: N
        - AttributeName: robinhood_points
          AttributeType: N
        - AttributeName: foodpanda_points
          AttributeType: N
        - AttributeName: grab_id
          AttributeType: S
        - AttributeName: robinhood_id
          AttributeType: S
        - AttributeName: foodpanda_id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
        - AttributeName: phone_number
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: username
          KeySchema:
            - AttributeName: username
              KeyType: HASH
          Projection: 
            ProjectionType: ALL
        - IndexName: grab_points
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: grab_points
              KeyType: RANGE
          Projection: 
            ProjectionType: ALL
        - IndexName: robinhood_points
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: robinhood_points
              KeyType: RANGE
          Projection: 
            ProjectionType: ALL
        - IndexName: foodpanda_points
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: foodpanda_points
              KeyType: RANGE
          Projection: 
            ProjectionType: ALL
        - IndexName: grab_id
          KeySchema:
            - AttributeName: grab_id
              KeyType: HASH
          Projection: 
            ProjectionType: ALL
        - IndexName: robinhood_id
          KeySchema:
            - AttributeName: robinhood_id
              KeyType: HASH
          Projection: 
            ProjectionType: ALL
        - IndexName: foodpanda_id
          KeySchema:
            - AttributeName: foodpanda_id
              KeyType: HASH
          Projection: 
            ProjectionType: ALL
        - IndexName: email
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection: 
            ProjectionType: ALL
        - IndexName: phone_number
          KeySchema:
            - AttributeName: phone_number
              KeyType: HASH
          Projection: 
            ProjectionType: ALL
      TableName: "BingsuUser"

Outputs:
  TestFunction:
    Description: "AddUser Lambda Function ARN"
    Value: !GetAtt TestFunction.Arn
  TestFunctionIamRole:
    Description: "Implicit IAM Role created for AddUser function"
    Value: !GetAtt TestFunctionRole.Arn
