AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bingsuUser

  Sample SAM Template for bingsuUser

Globals:
  Function:
    Timeout: 30
    Runtime: python3.8
    Environment:
      Variables:
        BINGSU_USER_TABLE_NAME: !Ref UserTable

Resources:
  TestFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: bingsuUser/
      Handler: app.lambda_handler
      
  AddUserFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: bingsuUser/
      Handler: app.add_user
      
  UpdateUserFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: bingsuUser/
      Handler: app.update_user
            
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: points
          AttributeType: N
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: points
          KeySchema:
            - AttributeName: points
              KeyType: HASH
          Projection: 
            ProjectionType: ALL
      TableName: "BingsuUser"

Outputs:
  TestFunction:
    Description: "AddUser Lambda Function ARN"
    Value: !GetAtt TestFunction.Arn
  TestFunctionIamRole:
    Description: "Implicit IAM Role created for AddUser function"
    Value: !GetAtt TestFunctionRole.Arn
