AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bingsuUser

  Sample SAM Template for bingsuUser

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    Runtime: python3.8

Resources:
  AddUserFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: bingsuUser/
      Handler: app.lambda_handler
            
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      TableName: "BingsuUser"

Outputs:
  AddUserFunction:
    Description: "AddUser Lambda Function ARN"
    Value: !GetAtt AddUserFunction.Arn
  AddUserFunctionIamRole:
    Description: "Implicit IAM Role created for AddUser function"
    Value: !GetAtt AddUserFunctionRole.Arn
